### ISSUE TITLE
Terraform Errors on creating CICD scenario.

### ISSUE THREAD

**Issue by HLOverflow** [RhinoSecurityLabs/cloudgoat#128]
Hi there,

I encountered a terraform error that I could not find a proper fix. 

I have done the following scenarios (not requiring extra resources) with no terraform issues except this CICD scenario:
- vulnerable_lambda
- iam_privesc_by_rollback
- cloud_breach_s3
- ec2_ssrf
- ecs_takeover
- rce_web_app
- ecs_efs_attack

![cloudgoat_create_cicd_error](https://user-images.githubusercontent.com/18380571/166673668-1e556e08-94d0-4f74-9f8d-3c512ea74e55.png)

My terraform version is as follows:
```
╰─# terraform --version
Terraform v1.1.9
on linux_amd64
```

I was also not able to overcome the error with the suggested `terraform init -upgrade` in the CICD terraform folder as seen below.

![cicd_terraform_init_upgrade](https://user-images.githubusercontent.com/18380571/166674561-6212d72b-c878-4b83-b226-245b9b691f50.png)

**Comment by RyanJarv** [comment]
@HLOverflow Hi there, thanks for letting us know. I believe this branch should resolve the 
 issue if you want to give that a try  https://github.com/RhinoSecurityLabs/cloudgoat/tree/fix/128-cicd-init.
 
You may need to delete the scenario before re-creating after the other branch is checked out it however, otherwise you will likely run into the same error.
