### ISSUE TITLE
tearaform regex partten should be change tfor version check

### ISSUE THREAD

**Issue by raja1rao** [RhinoSecurityLabs/cloudgoat#152]
as i am using new terraform version as
Terraform v1.3.0-alpha20220817
on linux_amd64
the regex partten used in cloudgoat.py "Terraform\ v(\d+\.\d+)\.\d+\s" will not match and through a error
 
"Terraform not found. Please install Terraform before using CloudGoat."

i fixed this issue by changing the regex "Terraform\ v(\d+\.\d+)" to get the version 

also in teraform oder version we can't get emullated or modify AWS due to the error below:

"Warning: Interpolation-only expressions are deprecated

  on ec2.tf line 27, in resource "aws_iam_role_policy_attachment" "cg-ec2-role-policy-attachment-s3":
  27:   role = "${aws_iam_role.cg-ec2-role.name}"

Error: Unsupported argument

  on rds.tf line 62, in resource "aws_db_instance" "cg-psql-rds":
  62:   db_name = "cloudgoat"

An argument named "db_name" is not expected here.

Error: Invalid resource type

  on s3.tf line 102, in resource "aws_s3_bucket_acl" "logs-s3-bucket-acl":
 102: resource "aws_s3_bucket_acl" "logs-s3-bucket-acl" {

The provider provider.aws does not support resource type "aws_s3_bucket_acl".

Error: Invalid resource type

  on s3.tf line 107, in resource "aws_s3_bucket_acl" "secret-s3-bucket-acl":
 107: resource "aws_s3_bucket_acl" "secret-s3-bucket-acl" {

The provider provider.aws does not support resource type "aws_s3_bucket_acl".

Error: Invalid resource type

  on s3.tf line 112, in resource "aws_s3_bucket_acl" "keystore-s3-bucket-acl":
 112: resource "aws_s3_bucket_acl" "keystore-s3-bucket-acl" {

The provider provider.aws does not support resource type "aws_s3_bucket_acl".

[cloudgoat] Error while running `terraform plan`.
    exit code: 1
    stdout: None
"

hopes it helps the community

**Comment by jdearmas** [comment]
Dear @raja1rao,

I wanted to take a moment to express my appreciation for creating an issue on GitHub. Your willingness to take the time to report the issue and provide feedback is truly commendable. It is this type of collaborative effort that makes open-source projects like ours so successful.

In regards to the issue(s) at hand,

- **The regular expression:**
The change in the regular expression you've proposed will likely cause errors.
The proposed regular expression will not match the minor version number.

- **The Terraform errors:**
In addition, the Terraform errors can be fixed by using a newer version of Terraform.

I encourage you to continue to submit any issues or suggestions you may have in the future. Your feedback is valuable and helps us to identify areas for improvement.

Best regards,
John
