### ISSUE TITLE
Having an issue accessing the site in ECS Takeover scenario

### ISSUE THREAD

**Issue by AbdullahRizwan101** [RhinoSecurityLabs/cloudgoat#154]
I am having an issue on accessing the url it shows at the end

![](https://i.imgur.com/MZ469IG.png)

I can't ping the url and the browser doesn't show any site as well

![](https://i.imgur.com/c2sHyhz.png)

Is there any fix for this ?

**Comment by jdearmas** [comment]
Hello! I performed the ecs_takeover scenario.
  I was able to connect to the AWS EC2 instance on commit [c5ca030a67970ec21f7bd2bc1cbb7ef3b97e5587].

  However, in order to help you with this issue more effectively, could you provide the following:

-   Provide the exact software version number or git commit hash this issue is on.

  And, if possible:

-   Provide the minimum amount of steps needed to reproduce your issue.
-   Provide the computer architecture of the machine you are using to run the software.

**Comment by YuvalZilber** [comment]
I have the same issue on master on two different computers.

in 
commit number: c5ce1dcb1c9c777bbfe5f210058a663d2c7b466a

Computer 1 (Mac):
MacBook Pro (16-inch, 2019)
macOS 12.5.1 (21G83)

Computer 2 (Linux):
The output of `cat /proc/version` :
Linux version 6.0.0-kali6-amd64 (devel@kali.org) (gcc-12 (Debian 12.2.0-10) 12.2.0, GNU ld (GNU Binutils for Debian) 2.39.50.20221208) #1 SMP PREEMPT_DYNAMIC Debian 6.0.12-1kali1 (2022-12-19)


Steps required:
./cloudgoat.py create ecs_takeover
cat ecs_takeover_*/start.txt
navigate to vuln-site address specified in the file.

**Comment by jdearmas** [comment]
Hello @YuvalZilber,

I notice that the git commit hash you are using is rather old. Does the error still persist for you when using commit  [c5ca030a67970ec21f7bd2bc1cbb7ef3b97e5587] or newer?

Note: For me, it takes several minutes for the service to become available.

**Comment by jdearmas** [comment]
A recent commit (a14783d) addressed an issue the ECS Takeover scenario startup. This may have resolved the issue you were experiencing. 

I will close this issue for now (partially due to inactivity). If you are still experiencing this issue, please let us know and we can reopen and readdress this issue.
