### ISSUE TITLE
Deployment error for  cloud_breach_s3

### ISSUE THREAD

**Issue by pswalia2u** [RhinoSecurityLabs/cloudgoat#156]
![image](https://user-images.githubusercontent.com/20887270/196000446-a7302558-7ff9-40ca-b2b8-911a4bc8a509.png)
./cloudgoat.py create cloud_breach_s3

**Comment by mr-b4rt0wsk1** [comment]
Had the same issue after using a Wi-Fi network I normally don't connect to. Was able to resolve by running `./cloudgoat.py config whitelist --auto` so that my new IP address range was added to `whitelist.txt`. The EC2 instance in this scenario won't get provisioned otherwise.

See this part of the README for reference: [https://github.com/RhinoSecurityLabs/cloudgoat#whitelist](https://github.com/RhinoSecurityLabs/cloudgoat#whitelist)

**Comment by DaveYesland** [comment]
Closing this for now. Feel free to reopen if you continue having this issue.
