### ISSUE TITLE
iam_privesc_by_rollback issue

### ISSUE THREAD

**Issue by akashkatare** [RhinoSecurityLabs/cloudgoat#40]
whenever i am executing below command  i am getting the error like below any solutions thanx in advance.. This i happening with in all challenges.even i tried on normal user and root level user as well still getting this error.
Or is there anything to setup before starting this challenge

Error: No valid credential sources found for AWS Provider.                                                          
        Please see https://terraform.io/docs/providers/aws/index.html for more information on
        providing credentials for the AWS Provider

  on provider.tf line 1, in provider "aws":
   1: provider "aws" {

[cloudgoat] Error while running `terraform plan`.
    exit code: 1
    stdout: None
    stderr: None

**Comment by rhino-sebastian** [comment]
Looks like this issue was caused by not having your AWS credentials configured. You can do this with the AWS cli `aws configure` ([https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-configure.html](link))

To test if your credentials are configured properly you can execute `aws sts get-caller-identity --profile <insert profile name>`.  👍
