### ISSUE TITLE
Terraform init state checks for plugins

### ISSUE THREAD

**Issue by kaushik853** [RhinoSecurityLabs/cloudgoat#62]
Hi,
How can i stop terraform from checking
Checking for available provider plugins...
Downloading plugin for provider "AWS" (hashicorp/aws) 
and making it use only the existing plugins

**Comment by RyanJarv** [comment]
It should be possible to possible to use a common plugin directory by passing `-plugin-dir` to terraform init when it is run by CloudGoat. This would need to be supported in the code though and it wouldn't guarantee the plugins wouldn't be fetched, but most likely would limit the number of times they need to be downloaded. 

Is there a reason you need to use already existing modules?

**Comment by RyanJarv** [comment]
I'm going to go ahead and close this due to lack of response. Realize it took a while to get back to you on this though, so if you are still interested in this feel free to open another issue and link to this one.

I think we can consider looking into this more if there's a good reason, but at the moment I'm not seeing a compelling reason (but maybe I'm missing something here!). Also open to accepting a PR for this if anyone is motivated enough to put something together for it.
